# Generated by Django 2.0.1 on 2018-01-24 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumb', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('title', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=100)),
            ],
        ),
    ]
